export const ROUTES = {
  HOME: "/",
  404: "/404",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  DASHBOARD_CATEGORIES: "/dashboard/categories",
  DASHBOARD_CREATE_CATEGORIES: "/dashboard/categories/create",
  DASHBOARD_UPDATE_CATEGORIES: "/dashboard/categories/update",
  DASHBOARD_USERS: "/dashboard/users",
  DASHBOARD_ADD_USERS: "/dashboard/users/create",
  DASHBOARD_UPDATE_USERS: "/dashboard/users/update",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  HIERARCHY: "/hierarchy",
} as const;
