name: reviewdog
run-name: reviewdog ESLint on push and pull request

on:
    push:
        branches:
            - main
    pull_request:
jobs:
    eslint:
        name: runner / eslint
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Installing Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - uses: haya14busa/action-cond@v1
              id: reporter
              with:
                  cond: ${{github.event_name == 'pull_request'}}
                  if_true: "github-pr-check"
                  if_false: "github-check"

            - name: Run ESLint with reviewdog
              uses: reviewdog/action-eslint@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: ${{ steps.reporter.outputs.value }}
                  eslint_flags: "src/"

            - name : Fail CI on ESLint errors
              run: npx eslint . --ext .js,.jsx,.ts,.tsx || exit $?
