name: reviewdog
on: 
    push:
        branches:
        - main
    pull_request:
        types:
        - opened
        - synchronize
        - reopened
        - labeled
        - unlabeled
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2 # v4.2.2
      - uses: reviewdog/action-eslint@v1.33.2 # v1.33.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: "src/"
